image: alpine

stages:
  - compile
  - docker_build
  - docker_push

compile:
  stage: compile
  script:
    - ./mvnw package

docker_build:
  stage: docker_build
  script:
    - docker build -t $CI_REGISTRY/vegaproject/notification-gateway/image ./

docker_push:
  stage: docker_push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/vegaproject/notification-gateway/image